import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      {/* NAV */}

      <main>
        <h1>Lets Build Hulu 2.0 Clone</h1>

        {/* RESULTS */}

      </main>
    </div>
  )
}
